// return  all the subsequence of a string.
// ex: abc
// output : 8 sub-sequence("", a,b,c,ab,bc,ac,abc)
// A subsequence of a string is the one which is generated by deleting 0 or
// more characters from the string and keeping the other character at the same order.
// a sub-sequence is non-continuous but sub-string is continuous.
// ex: from string :"abc", ac is a subsequence but it is not substring.
// formula: is a string has 'n' characters, it will have exactly
// 2^n no. of total subsequence

#include <bits/stdc++.h>

using namespace std;

int subSequence(string input, string output[])
{
    if (input.empty())
    {
        output[0] = "";
        return 1;
    }

    string smallString = input.substr(1);
    int smallOutputSize = subSequence(smallString, output);

    for (int i = 0; i < smallOutputSize; i++)
    {
        output[i + smallOutputSize] = input[0] + output[i];
    }
    return 2 * smallOutputSize;
}

int main()
{

    string input;

    cout << "enter input string: ";
    cin >> input;
    int size = pow(2, input.size());
    string output[size];
    int count = subSequence(input, output);

    for (int i = 0; i < count; i++)
    {
        cout << output[i] << endl;
    }

    return 0;
}